spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.250.78:3306/ldf_course?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 19981102
  application:
    name: system
server:
  port: 9002
  servlet:
    context-path: /system

logging:
  level:
     com.ldf.system.mapper: trace



